<?php

namespace App\Services;

use App\Models\Application;
use App\Models\ApplicationDocument;
use App\Models\User;
use Barryvdh\DomPDF\Facade\Pdf as DomPdf;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\Storage;

class CashflowsSwitchNoticeService
{
    /**
     * Generate the Cashflows-to-Cardstream switch notice as a plain PDF (no DocuSign
     * envelope involved) and attach it to the application as a normal document, so it
     * rides along in Document Library / the CardStream submission email exactly like
     * any other uploaded document.
     */
    public function generate(Application $application, string $accountName, ?UploadedFile $logo, User $generatedBy): ApplicationDocument
    {
        $logoDataUri = $this->resolveLogoDataUri($application, $logo);

        $html = view('pdfs.cashflows-switch-notice', [
            'account_name' => $accountName,
            'logo_data_uri' => $logoDataUri,
        ])->render();

        $pdfContent = DomPdf::loadHTML($html)->output();

        $filename = 'cashflows-switch-notice-'.time().'.pdf';
        $path = "application_documents/{$application->id}/{$filename}";
        Storage::disk('public')->put($path, $pdfContent);

        $previous = ApplicationDocument::getLatestVersion($application->id, ApplicationDocument::CATEGORY_CASHFLOWS_SWITCH_NOTICE);

        $document = ApplicationDocument::create([
            'application_id' => $application->id,
            'document_type' => 'application/pdf',
            'document_category' => ApplicationDocument::CATEGORY_CASHFLOWS_SWITCH_NOTICE,
            'file_path' => $path,
            'original_filename' => $filename,
            'uploaded_by' => $generatedBy->id,
            'uploaded_by_type' => 'user',
            'status' => 'uploaded',
            'parent_document_id' => $previous?->id,
        ]);

        if ($previous) {
            $previous->update([
                'is_superseded' => true,
                'superseded_by_id' => $document->id,
                'superseded_at' => now(),
            ]);
        }

        if (! $application->status->cashflows_switch_notice_sent_at) {
            $application->status->transitionTo(
                'cashflows_switch_notice_sent',
                "Cashflows switch notice generated by {$generatedBy->name}"
            );
        }

        return $document;
    }

    /**
     * DomPDF needs the image inline (a data URI) rather than a URL it would have to
     * fetch itself, so the account's own uploaded logo - or a one-off override from the
     * modal - gets embedded directly rather than linked.
     */
    private function resolveLogoDataUri(Application $application, ?UploadedFile $logo): ?string
    {
        if ($logo) {
            return 'data:'.$logo->getMimeType().';base64,'.base64_encode($logo->get());
        }

        $photoPath = $application->account->photo_path ?? null;

        if ($photoPath && Storage::disk('public')->exists($photoPath)) {
            $mimeType = Storage::disk('public')->mimeType($photoPath);
            $contents = Storage::disk('public')->get($photoPath);

            return "data:{$mimeType};base64,".base64_encode($contents);
        }

        return null;
    }
}
