<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Amendment to {{ $document_type }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            line-height: 1.6;
            color: #333;
            margin: 40px;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            padding-bottom: 20px;
            border-bottom: 2px solid #0066cc;
        }
        .header h1 {
            color: #0066cc;
            margin: 0 0 10px 0;
        }
        .info-section {
            margin-bottom: 30px;
            background: #f8f9fa;
            padding: 15px;
            border-radius: 5px;
        }
        .info-row {
            margin-bottom: 8px;
        }
        .info-label {
            font-weight: bold;
            display: inline-block;
            width: 150px;
        }
        .changes-table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        .changes-table th,
        .changes-table td {
            border: 1px solid #ddd;
            padding: 12px;
            text-align: left;
        }
        .changes-table th {
            background-color: #0066cc;
            color: white;
            font-weight: bold;
        }
        .changes-table tr:nth-child(even) {
            background-color: #f8f9fa;
        }
        .old-value {
            text-decoration: line-through;
            color: #dc3545;
        }
        .new-value {
            color: #28a745;
            font-weight: bold;
        }
        .footer {
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #ddd;
            font-size: 10px;
            color: #666;
            text-align: center;
        }
        .notice {
            background: #fff3cd;
            border-left: 4px solid #ffc107;
            padding: 15px;
            margin: 20px 0;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>AMENDMENT NOTICE</h1>
        <h2>{{ $document_type }}</h2>
    </div>

    <div class="info-section">
        <div class="info-row">
            <span class="info-label">Application:</span>
            <span>{{ $application->name }}</span>
        </div>
        <div class="info-row">
            <span class="info-label">Merchant:</span>
            <span>{{ $application->account->name }}</span>
        </div>
        <div class="info-row">
            <span class="info-label">Amendment Date:</span>
            <span>{{ $amended_at->format('d/m/Y H:i') }}</span>
        </div>
        <div class="info-row">
            <span class="info-label">Amended By:</span>
            <span>{{ $amended_by }}</span>
        </div>
    </div>

    <div class="notice">
        <strong>Important:</strong> This document records amendments made to the original {{ $document_type }}. 
        The original signed document remains valid and should be retained alongside this amendment.
    </div>

    <h3>Changes Made</h3>
    
    @if(count($changes) > 0)
        <table class="changes-table">
            <thead>
                <tr>
                    <th width="30%">Field</th>
                    <th width="35%">Original Value</th>
                    <th width="35%">New Value</th>
                </tr>
            </thead>
            <tbody>
                @foreach($changes as $change)
                    <tr>
                        <td><strong>{{ $change['field'] }}</strong></td>
                        <td><span class="old-value">{{ $change['old_value'] }}</span></td>
                        <td><span class="new-value">{{ $change['new_value'] }}</span></td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @else
        <p>No changes were recorded.</p>
    @endif

    <div class="footer">
        <p>
            Generated by G2Pay Portal on {{ now()->format('d/m/Y H:i:s') }}<br>
            This is an official amendment record. Keep this document with the original signed {{ $document_type }}.
        </p>
    </div>
</body>
</html>